version: '3.9'

services:
  msms_web:
    build:
      context: .
      dockerfile: MSMS.Web/Dockerfile.dev
    environment:
      - ConnectionStrings__DefaultConnection=Server=msms_db;Database=MSMSDb;User=sa;Password=DevPassword123!;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - msms_db
    ports:
      - 5050:8080
      - 5051:8081
    volumes:
      - .:/src
    restart: "no"
    stdin_open: true
    tty: true

  msms_db:
    environment:
      SA_PASSWORD: DevPassword123!
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - minecraft_dev_data:/var/opt/mssql
    restart: "no"

volumes:
  minecraft_dev_data:
