services:
  msms_web:
    container_name: msms_web_dev
    environment:
      - ConnectionStrings__DefaultConnection=Server=${DATABASE_SERVER};Database=${DATABASE_NAME};User=${DATABASE_USER};Password=${DATABASE_PASSWORD};TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
    restart: "no"
    depends_on:
      - msms_db
    ports:
      - 5050:8080
      - 5051:8081
    volumes:
      - .:/src
    tty: true

  msms_db:
    container_name: msms_db_dev
    environment:
      - MSSQL_SA_PASSWORD=${DATABASE_PASSWORD}
      - ACCEPT_EULA=Y
    ports:
      - 1434:1433
    volumes:
      - msms_dev_data:/var/opt/mssql
    restart: "no"

volumes:
  msms_dev_data:
