FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /src
EXPOSE 8080
EXPOSE 8081

COPY ["MSMS.Web/MSMS.Web.csproj", "MSMS.Web/"]
COPY ["MSMS.Infrastructure/MSMS.Infrastructure.csproj", "MSMS.Infrastructure/"]
COPY ["MSMS.Core/MSMS.Core.csproj", "MSMS.Core/"]
RUN dotnet restore MSMS.Web/
COPY . .
WORKDIR /src/MSMS.Web

CMD ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:8080;https://0.0.0.0:8081"]
